[server]
runOnSave = true

[theme]
base="dark"
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
baseRadius = "0.3rem"
showWidgetBorder = false
font = "sans-serif"
codeFont = "monospace"
baseFontSize = 20
codeFontSize="0.875rem"
headingFontSizes = ["39.5px", "32px", "24px"]
headingFontWeights = [900, 700, 700]
buttonRadius = "full"

[theme.sidebar]
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
backgroundColor = "#1c1e26ff"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"